Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(1,"SNAP");
Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(2,"CCAP");
Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(3,"Medicaid");
Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(4,"Medicare");
Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(5,"QHP");
Insert into PLAN_CATEGORY_MASTER(CATEGORY_ID,CATEGORY_NAME) values(6,"NJP");
